(function(d){var e=window.AmazonUIPageJS||window.P,l=e._namespace||e.attributeErrors,a=l?l("DetailPageMobileIconFarmAssets@common","DetailPageMobileIconFarm"):e;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,e,l){d.when("A","ready").register("get-icon-farm-page-state",function(a){return{parseJSON:function(c){var b;try{b=a.$("#"+c).find('script[data-a-state\x3d"{"key":"iconfarm-state"}"]').html()}catch(f){console.log(f.message)}b?c=a.$.parseJSON(b):(a.state.parse(),
c=a.state("iconfarm-state"));return c}}});d.declare("iconfarm-metrics-constants",{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",METRIC_TYPE:{GLANCE_VIEW:"GLANCE_VIEW",ICON_CLICK:"ICON_CLICK",SECONDARY_PAGE_OPEN:"SECONDARY_PAGE_OPEN",SECONDARY_PAGE_CLOSE:"SECONDARY_PAGE_CLOSE",FULL_RETURN_POLICY:"FULL_RETURN_POLICY",PAGE_DATA_MISSING:"PAGE_DATA_MISSING",ABSENT:"ABSENT"},REF_MARKER_PREFIX:{ICON_FARM_WIDGET:"iconfarm_wid",AMAZON_DELIVERED:"iconfarm_ad",
RETURNS_POLICY:"iconfarm_rp",PAY_ON_DELIVERY:"iconfarm_pod",WARRANTY:"iconfarm_wr",EASY_CARE:"iconfarm_ec",AMAZON_PROTECT:"iconfarm_ap",NO_CONTACT_DELIVERY:"iconfarm_ncd",GENERIC_RETURN_POLICY:"iconfarm_grp",MULTIPLE_SPECIFIC_RETURN_POLICY:"iconfarm_msrp",SINGLE_SPECIFIC_RETURN_POLICY:"iconfarm_ssrp",PAY_ON_DELIVERY_ACTIVE:"iconfarm_pod_active",PAY_ON_DELIVERY_INACTIVE:"iconfarm_pod_inactive",WARRANTY_EU:"iconfarm_wr_eu",AMAZON_MANAGED_DELIVERY:"iconfarm_amd",AMAZON_DELIVERED_MENA:"iconfarm_ad_mena",
SAFE_PAYMENTS:"iconfarm_sp",STATIC_RETURNS_POLICY:"iconfarm_srp",GENERIC_RETURNS_POLICY:"iconfarm_grp",SUPPORT_POLICY:"iconfarm_supp",RETURNS_POLICY_MENA:"iconfarm_rp_mena"},REF_MARKER_SUFFIX:{GLANCE_VIEW:"_gv",ICON_CLICK:"_clk",SECONDARY_PAGE_OPEN:"_sp_op",SECONDARY_PAGE_CLOSE:"_sp_cl",FULL_RETURN_POLICY:"_frp",ABSENT:"_noavail"}});d.when("A","iconfarm-return-policy-metric-logger","iconfarm-pay-on-delivery-metric-logger","iconfarm-default-metric-logger").register("iconfarm-icon-metric-factory",function(a,
c,b,f){return{getIconMetric:function(a){switch(a){case "RETURNS_POLICY":return c;case "PAY_ON_DELIVERY":return b;default:return f}}}});d.when("A","iconfarm-metricService","iconfarm-metrics-constants","get-icon-farm-page-state","iconfarm-icon-metric-factory","ready").register("iconfarm-metricLogger",function(a,c,b,f,d){return{log:function(c,g,e){if(c&&g&&b.REF_MARKER_PREFIX[c]&&b.REF_MARKER_SUFFIX[g]){var h=f.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV);h&&d.getIconMetric(c).log(c,g,a.$.extend(!0,
{asin:h.asin,merchantId:h.merchantId},e))}}}});d.when("A","iconfarm-metric-cache","ready").register("iconfarm-metricService",function(a,c){return{log:function(b){if(c.add(b)){var f="/ref\x3d"+b.ref,f=f+("?pageAsin\x3d"+b.asin),f=f+("\x26pageType\x3d"+(a.capabilities?a.capabilities.mobile?a.capabilities.isAmazonApp?"DetailWebView":"DetailAW":"Detail":"")),f=f+"\x26subPageType\x3dIconFarm"+("\x26merchantId\x3d"+b.merchantId);a.get("/gp/product/ajax/dpx-metrics-handler.html"+f)}}}});d.when("A","ready").register("iconfarm-postmetric",
function(){return{postCountMetric:function(a){if("undefined"!==typeof a){var c=e.ue;if(c){var b=c.count(a)||0;c.count(a,b+1)}}},postTimeMetric:function(a,c){if("undefined"!==typeof a&&"undefined"!==typeof c){var b=e.ue;b&&b.count(a,c)}}}});d.when("A","ready").register("iconfarm-metric-cache",function(a){var c=[],b=function(b){if(!(b&&b.asin&&b.merchantId&&b.ref))return!1;var d=!1;a.each(c,function(a,c){a.asin===b.asin&&a.merchantId===b.merchantId&&a.ref===b.ref&&(d=!0)});return d};return{isPresent:b,
add:function(a){return a&&a.asin&&a.merchantId&&a.ref?b(a)?!1:(c.push(a),!0):!1},reset:function(){c=[]}}});d.when("A","iconfarm-metricService","iconfarm-metrics-constants","iconfarm-postmetric","ready").register("iconfarm-default-metric-logger",function(a,c,b,f){return{log:function(d,k,g){c.log(a.$.extend(!0,g,{ref:b.REF_MARKER_PREFIX[d]+b.REF_MARKER_SUFFIX[k]}));f.postCountMetric(b.REF_MARKER_PREFIX[d]+b.REF_MARKER_SUFFIX[k])}}});d.when("A","iconfarm-metricService","iconfarm-metrics-constants","iconfarm-postmetric",
"get-icon-farm-page-state","ready").register("iconfarm-return-policy-metric-logger",function(a,c,b,d,e){var k=function(){var a=e.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV);if(a&&a.RETURNS_POLICY&&a.RETURNS_POLICY.secondaryViewData&&a.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies)switch(a.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies.length){case 0:return"GENERIC_RETURN_POLICY";case 1:return"SINGLE_SPECIFIC_RETURN_POLICY";default:return"MULTIPLE_SPECIFIC_RETURN_POLICY"}};return{log:function(g,
e,h){g=k()||g;c.log(a.$.extend(!0,h,{ref:b.REF_MARKER_PREFIX[g]+b.REF_MARKER_SUFFIX[e]}));d.postCountMetric(b.REF_MARKER_PREFIX[g]+b.REF_MARKER_SUFFIX[e])}}});d.when("A","iconfarm-metricService","iconfarm-metrics-constants","iconfarm-postmetric","get-icon-farm-page-state").register("iconfarm-pay-on-delivery-metric-logger",function(a,c,b,d,e){return{log:function(k,g,l){var h;h=(h=e.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV))&&h.PAY_ON_DELIVERY&&h.PAY_ON_DELIVERY.isEligible?h.PAY_ON_DELIVERY.isEligible?
"PAY_ON_DELIVERY_ACTIVE":"PAY_ON_DELIVERY_INACTIVE":void 0;k=h||k;c.log(a.$.extend(!0,l,{ref:b.REF_MARKER_PREFIX[k]+b.REF_MARKER_SUFFIX[g]}));d.postCountMetric(b.REF_MARKER_PREFIX[k]+b.REF_MARKER_SUFFIX[g])}}})});
/* ******** */
(function(f){var g=window.AmazonUIPageJS||window.P,h=g._namespace||g.attributeErrors,a=h?h("DetailPageMobileIconFarmAssets@desktop","DetailPageMobileIconFarm"):g;a.guardFatal?a.guardFatal(f)(a,window):a.execute(function(){f(a,window)})})(function(f,g,h){f.when("A","a-popover","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","ready").register("icon-farm-desktop-popover",function(a,n,e,b,d){var c=function(c){var e=c.data("name");a.off("a:popover:beforeShow:"+e);a.on("a:popover:beforeShow:"+
e,function(a){b.log(e,d.METRIC_TYPE.ICON_CLICK);b.log(e,d.METRIC_TYPE.SECONDARY_PAGE_OPEN)});a.off("a:popover:beforeHide:"+e);a.on("a:popover:beforeHide:"+e,function(a){b.log(e,d.METRIC_TYPE.SECONDARY_PAGE_CLOSE)})};return{init:function(){for(var b=a.$(e.ICON_FARM_CONTAINER_CLASS),d=0;d<b.length;d++){var k=a.$(b[d]),f=k.data(e.TYPE_PARAM);if(f&&f===e.TYPE_PARAM_VALUE_CUSTOM_POP_OVER){var f=k,m=a.$("#"+f.data(e.POPOVER_CONTENT_PARAM)),m={activate:e.POPOVER_ACTIVATION,position:e.POPOVER_POSITION,width:e.POPOVER_WIDTH,
inlineContent:m.html(),name:f.data("name")};n.create(f,m);c(k)}}}}});f.when("A","get-icon-farm-page-state","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","ready").register("icon-farm-desktop-returns-policy",function(a,f,e,b,d){a.declarative("returns-policy-url","click",function(a){b.log("RETURNS_POLICY",d.METRIC_TYPE.FULL_RETURN_POLICY);a=f.parseJSON(e.ICON_FARM_PAGE_STATE_HOLDER_DIV);a.RETURNS_POLICY.secondaryViewData.fullReturnPolicyURL="https://www.amazon.in/gp/help/customer/display.html/?ie\x3dUTF8\x26nodeId\x3d201149900";
a.RETURNS_POLICY.secondaryViewData.genericReturnPolicyURL="https://www.amazon.in/gp/help/customer/display.html?nodeId\x3d202111910";g.open(a.RETURNS_POLICY.secondaryViewData.genericReturnPolicyURL,"_blank")});a.off("a:popover:beforeShow:return-policy-secondary-view");a.on("a:popover:beforeShow:return-policy-secondary-view",function(a){b.log("RETURNS_POLICY",d.METRIC_TYPE.ICON_CLICK);b.log("RETURNS_POLICY",d.METRIC_TYPE.SECONDARY_PAGE_OPEN)});a.off("a:popover:beforeHide:return-policy-secondary-view");
a.on("a:popover:beforeHide:return-policy-secondary-view",function(a){b.log("RETURNS_POLICY",d.METRIC_TYPE.SECONDARY_PAGE_CLOSE)});return{init:function(){var c=f.parseJSON(e.ICON_FARM_PAGE_STATE_HOLDER_DIV),b=a.$(e.ICON_FARM_SECONDARY_VIEW_HOLDER_ID);if(c&&c.RETURNS_POLICY&&c.RETURNS_POLICY.secondaryViewData&&c.RETURNS_POLICY.secondaryViewData.glLevelReturn)if(c&&!c.returnPolicyContent){var d={responseType:"html"};c.RETURNS_POLICY.secondaryViewData.fullReturnPolicyURL="https://www.amazon.in/gp/help/customer/display.html/?ie\x3dUTF8\x26nodeId\x3d201149900";
c.RETURNS_POLICY.secondaryViewData.genericReturnPolicyURL="https://www.amazon.in/gp/help/customer/display.html?nodeId\x3d202111910";d.data=JSON.stringify(c.RETURNS_POLICY.secondaryViewData);d.data&&a.ajax("/gp/product/features/icon-farm/iconFarm-sv-loader.html",{method:"POST",params:d,success:function(d){d&&b&&b.length&&(c.returnPolicyContent=d,a.state(e.ICON_FARM_STATE,c),b.html(d),c.RETURNS_POLICY.secondaryViewData.fullReturnPolicyURL&&a.$(".full-return-policy").attr("href",c.RETURNS_POLICY.secondaryViewData.fullReturnPolicyURL))}})}else c&&
c.returnPolicyContent&&b&&b.length&&(b.html(c.returnPolicyContent),c.RETURNS_POLICY.secondaryViewData.fullReturnPolicyURL&&a.$(".full-return-policy").attr("href",c.RETURNS_POLICY.secondaryViewData.fullReturnPolicyURL))}}});f.when("A","IconFarmPageStateParserService","icon-farm-desktop-popover","icon-farm-desktop-returns-policy","iconfarm-metricLogger","icon-farm-constants","iconfarm-metrics-constants","iconfarm-metric-cache","atf","ready").execute(function(a,f,e,b,d,c,l,g){function k(){g.reset();
a.loadImageManually(a.$(".icon-box"));e.init();b.init();h()}var h=function(){var c=a.$("#icon-farm-widget");c&&c.length?d.log("ICON_FARM_WIDGET",l.METRIC_TYPE.GLANCE_VIEW):d.log("ICON_FARM_WIDGET",l.METRIC_TYPE.ABSENT);(c=a.$(".icon-container"))&&c.length&&c.each(function(){d.log(a.$(this).data("name"),l.METRIC_TYPE.GLANCE_VIEW)})};k();a.on("a:pageUpdate",function(){var b;a:{try{if(a.$("#"+c.ICON_FARM_V2_FEATURE_DIV).find("script").length){b=c.ICON_FARM_V2_FEATURE_DIV;break a}if(a.$("#"+c.ICON_FARM_V2_PRIMARY_FEATURE_DIV).find("script").length){b=
c.ICON_FARM_V2_PRIMARY_FEATURE_DIV;break a}d.log("ICON_FARM_WIDGET",l.PAGE_DATA_MISSING)}catch(e){d.log("ICON_FARM_WIDGET",l.PAGE_DATA_MISSING)}b=void 0}b&&f.isNewState(b,c.ICON_FARM_STATE)&&(b=f.processState(b,c.ICON_FARM_STATE),a.objectIsEmpty(b)||k())})});f.declare("icon-farm-constants",{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_V2_FEATURE_DIV:"iconfarmv2_feature_div",ICON_FARM_V2_PRIMARY_FEATURE_DIV:"iconFarmV2InsidePrimary_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",
ICON_FARM_CONTAINER_CLASS:".icon-container",ICON_FARM_SECONDARY_VIEW_HOLDER_ID:"#icon-farm-secondary-view-holder",ICON_FARM_STATE:"iconfarm-state",POPOVER_ACTIVATION:"onclick",POPOVER_POSITION:"triggerBottom",POPOVER_WIDTH:"533",POPOVER_CONTENT_PARAM:"iconContent",TYPE_PARAM:"type",TYPE_PARAM_VALUE:"bottom-sheet",TYPE_PARAM_VALUE_CUSTOM_POP_OVER:"custom-pop-over"});(function(){f.when("A","atf","ready").register("IconFarmPageStateParserService",function(a){function f(e,b){b='script[data-a-state\x3d"'+
JSON.stringify({key:b})+'"]';return a.$("#"+e).find(b)}return{processState:function(e,b){var d;try{var c=f(e,b),g=c[0];d=c.html();var h=a.parseJSON(d);a.state(b,h);a.$.data(g,"state_processed",!0);return h}catch(k){console.log(k)}return a.state(b)},isNewState:function(e,b){try{return!a.$.data(f(e,b)[0],"state_processed")}catch(d){console.warn("Unable to determine state status",d)}return!1}}})})()});
/* ******** */
